Work:
   email_ids: 
      Company-A: mhamdansulaiman@gmail.com
      Company-B: mhamdansulaiman@gmail.com
   calendar_ids:
      Company-A: qftvluod2pvrcv12d3eh54rrio@group.calendar.google.com
      Company-B: mhshamdan@outlook.com
Personal:
   email_ids:
      Personal: mhamdansulaiman@gmail.com
      Family: mhamdansulaiman@gmail.com
   calendar_ids:
      Personal: mhamdansulaiman@gmail.com
      Family: mnvir8sik8vjgatmj3koob4mt8@group.calendar.google.com
Cricket:
   email_ids:
      PSL Schedule: 99randomspawn@gmail.com
   calendar_ids:
      PSL Schedule: 6d428jc9497ucmtkru0q1rp1ps@group.calendar.google.com