Work:
   email_ids: 
      Internship: mhamdansulaiman@gmail.com
      Company-A: mhshamdan@outlook.com
   calendar_ids:
      Internship: qftvluod2pvrcv12d3eh54rrio@group.calendar.google.com
      Company-A: mhshamdan@outlook.com
Personal:
   email_ids:
      Personal: mhamdansulaiman@gmail.com
      Family: mhamdansulaiman@gmail.com
   calendar_ids:
      Personal: mhamdansulaiman@gmail.com
      Family: mnvir8sik8vjgatmj3koob4mt8@group.calendar.google.com
Cricket:
   email_ids:
      PSL Schedule: 99randomspawn@gmail.com
   calendar_ids:
      PSL Schedule: 6d428jc9497ucmtkru0q1rp1ps@group.calendar.google.com